#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Sep 08 23:11:04 EDT 2024
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim systolic_array_tb_behav -key {Behavioral:sim_1:Functional:systolic_array_tb} -tclbatch systolic_array_tb.tcl -view /home/charlie/Workspace/pq_research/hwpq_qw2246/systolic_array/vivado_systolic_array/open_list_queue_tb_behav.wcfg -log simulate.log"
xsim systolic_array_tb_behav -key {Behavioral:sim_1:Functional:systolic_array_tb} -tclbatch systolic_array_tb.tcl -view /home/charlie/Workspace/pq_research/hwpq_qw2246/systolic_array/vivado_systolic_array/open_list_queue_tb_behav.wcfg -log simulate.log

